Added chain transaction in user_activity.
priori-capital/wallet-indexer pull request #4
Opened 2023-03-09 10:23 UTC by shubhampatwa

2023-03-09 10:36 UTC, ptsayli requested changes

2023-03-09 10:36 UTC, ptsayli commented on src/sync/events/utils.ts
> +                onChainTransaction.push({
All transactions are on chain transactions, change variable.

2023-03-09 10:36 UTC, ptsayli commented on src/sync/events/utils.ts
> +          await processOnChainData(chainId, { ftTransferEvents: onChainTransaction });
I think we don't need to go through `ft-transfer-events` here. We can directly make an object and add it to the `transferActivity` queue.
Please check if I'm thinking right. @shubhampatwa

2023-03-09 10:38 UTC, shubhampatwa commented on src/sync/events/utils.ts
> +          await processOnChainData(chainId, { ftTransferEvents: onChainTransaction });
yeah exactly we need to do that, Need clarity on batchIndex
@ptsayli

2023-03-09 11:00 UTC, shubhampatwa commented on src/sync/events/utils.ts
> +              if (!bn(tx.value).isZero()) {
@spunkypanda check here

2023-03-09 11:02 UTC, spunkypanda commented on src/sync/events/utils.ts
> +              if (!bn(tx.value).isZero()) {
Thanks

2023-03-09 11:03 UTC, spunkypanda approved these changes

2023-03-10 02:26 UTC, ptsayli commented
https://github.com/priori-capital/wallet-indexer/pull/4/files#diff-c1fa3b6bc0bc52056ea900ead878b3706dafbe3bfc81deac8d7c86ec21b06b20R110
As we are storing native assets also, We need to create a new event kind. @shubhampatwa

2023-03-10 03:42 UTC, shubhampatwa commented
> https://github.com/priori-capital/wallet-indexer/pull/4/files#diff-c1fa3b6bc0bc52056ea900ead878b3706dafbe3bfc81deac8d7c86ec21b06b20R110 As we are storing native assets also, We need to create a new event kind. @shubhampatwa

If I create a new event kind, I will call the same function only to save in user activity, as we are not storing the kind column, do we need to create a new event kind then also? @ptsayli

2023-03-10 08:54 UTC, ptsayli approved these changes
Perfect

2023-03-10 08:54 UTC, merged